/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AiCfoRouteImport } from './routes/ai-cfo'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiCfoChatRouteImport } from './routes/api.ai-cfo.chat'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCfoRoute = AiCfoRouteImport.update({
  id: '/ai-cfo',
  path: '/ai-cfo',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCfoChatRoute = ApiAiCfoChatRouteImport.update({
  id: '/api/ai-cfo/chat',
  path: '/api/ai-cfo/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-cfo': typeof AiCfoRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/api/ai-cfo/chat': typeof ApiAiCfoChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-cfo': typeof AiCfoRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/api/ai-cfo/chat': typeof ApiAiCfoChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-cfo': typeof AiCfoRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/mcp': typeof McpRoute
  '/api/ai-cfo/chat': typeof ApiAiCfoChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-cfo'
    | '/connect'
    | '/dashboard'
    | '/mcp'
    | '/api/ai-cfo/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-cfo'
    | '/connect'
    | '/dashboard'
    | '/mcp'
    | '/api/ai-cfo/chat'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-cfo'
    | '/connect'
    | '/dashboard'
    | '/mcp'
    | '/api/ai-cfo/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiCfoRoute: typeof AiCfoRoute
  ConnectRoute: typeof ConnectRoute
  DashboardRoute: typeof DashboardRoute
  McpRoute: typeof McpRoute
  ApiAiCfoChatRoute: typeof ApiAiCfoChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-cfo': {
      id: '/ai-cfo'
      path: '/ai-cfo'
      fullPath: '/ai-cfo'
      preLoaderRoute: typeof AiCfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-cfo/chat': {
      id: '/api/ai-cfo/chat'
      path: '/api/ai-cfo/chat'
      fullPath: '/api/ai-cfo/chat'
      preLoaderRoute: typeof ApiAiCfoChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiCfoRoute: AiCfoRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRoute,
  McpRoute: McpRoute,
  ApiAiCfoChatRoute: ApiAiCfoChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
